### PR TITLE
Extra OpenAD attempts

### PR DESCRIPTION
**Pull request by timothyas**
@mjlosch I'm opening this PR on your branch, but (of course) don't merge it unless it actually fixes problems. I'm opening the PR because the specific OpenAD global_oce_optim test is only triggered by PRs, not simply by pushing and I'm not sure how else to trigger (or otherwise run) that experiment.

I'll just give some pushes here and there when I get the chance to try to get OpenAD to do what we want.

### CODE REVIEW

**Comment by timothyas** [comment]
Hmm.. It looks like you need to approve running workflows on your branch for the tests to be triggered. I'll just close this for now and open it on the MITgcm main repo explaining what I'm doing.

**Comment by timothyas** [comment]
Actually I can trigger those adjoint builds when I push to my branch just by commenting out this line in the workflows yaml file:
https://github.com/MITgcm/MITgcm/blob/f7f5217b7960be20c6e3fd6f8eaadaf21e22d06b/.github/workflows/build_testing.yml#L96
So I don't need to open a PR. As I said I'll run the occasional test in the background when I can. If any of my attempts strike gold, I'll open a PR on your `verif_ecco_ctrl_dep` branch

**Comment by mjlosch** [comment]
@timothyas I would like to learn this trick. What do I need to do to trigger a specific test on a non-PR branch?

**Comment by mjlosch** [comment]
@timothyas what I didn't realise is that each time I push anything to my fork, it triggers the default test suite! Is that intentional? I guess the first lines in the yml file define that. I have to ask @jahn if we want to reduce this to just pushing to open PRs? For now I have edited the yml on a separate branch test_deprecated so that it just run 2 tests whenever I push. That seems to work.

**Pull request closed without merging**
